//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4961
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashInterfaceViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashInterfaceViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///
        ///
        ///	///////////////////////////////////////////////////////////////////////////////////
        ///	///////////////////////////////////////////////////////////////////////////////////
        ///	///			以下是界面使用VC事件的代码				///
        ///	///			     可以直接拷贝使用					///
        ///	///////////////////////////////////////////////////////////////////////////////////
        ///	///////////////////////////////////////////////////////////////////////////////////
        ///
        ///	
        ///	/**
        ///	 * 初始化事件监听
        ///	 */
        ///	private function initListener() {{
        ///{0}
        ///	}}
        ///	
        ///	/**
        ///	 * 清除资源 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string allEventCode {
            get {
                return ResourceManager.GetString("allEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新程序已经下载，文件与当前应用程序同目录，
        ///名字为：{0}
        ///
        ///下面有两条关于版本更新建议：
        ///1.关闭并删除这个旧版本的应用程序。
        ///2.把新版本的程序改名为&quot;FlashInterfaceViewer.exe&quot; 的本地化字符串。
        /// </summary>
        internal static string appDowened {
            get {
                return ResourceManager.GetString("appDowened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序更新失败。
        ///应该是下载失败了。
        ///找高帆直接要程序吧。 的本地化字符串。
        /// </summary>
        internal static string appDownError {
            get {
                return ResourceManager.GetString("appDownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/**
        ///	 * {0}
        ///	 * @param	callBackName	回调函数名字
        ///	 * @param	thisObj			回调函数所在对象
        ///	 * @param	isRemove		是否是移除事件
        ///	 */
        ///	public static function {1}(callBackName:String, thisObj:Object, isRemove:Boolean) {{
        ///		
        ///		/*
        ///		 代理类.{1}(&quot;{1}&quot;, this);
        ///			
        ///		/**
        ///		 * {2}
        ///		 * @param	e	VC事件，参数都在e.data里
        ///		 /
        ///		private function {1}(e:CppEvent) {{
        ///			
        ///{3}
        ///		}}
        ///		*/
        ///		
        ///		GCpp.eventListener(&quot;{4}&quot;, thisObj, callBackName, isRemove);
        ///	}} 的本地化字符串。
        /// </summary>
        internal static string asEventTmp {
            get {
                return ResourceManager.GetString("asEventTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/**
        ///	 * {0}
        ///	 */
        ///	public static function {1}({2}){3} {{
        ///		{5}GCpp.callMethod(&quot;{1}&quot;{4});
        ///	}} 的本地化字符串。
        /// </summary>
        internal static string asFuncTmp {
            get {
                return ResourceManager.GetString("asFuncTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/**
        ///	 * {0}
        ///	 * @param	e	VC事件，参数都在e.data里
        ///	 */
        ///	private function {1}(e:CppEvent) {{
        ///		
        ///{2}
        ///	}} 的本地化字符串。
        /// </summary>
        internal static string eventHandlerCode {
            get {
                return ResourceManager.GetString("eventHandlerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///////////////////////////////////////////////////
        /////路径：{0}
        /////以下是【{1}】所有的{2}
        ///////////////////////////////////////////////////
        ///
        ///
        ///{3} 的本地化字符串。
        /// </summary>
        internal static string folderTitleTmp {
            get {
                return ResourceManager.GetString("folderTitleTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法名：{0}
        ///
        ///说明：	{1}
        ///
        ///返回：	{2}
        ///
        ///参数：
        ///{3}
        ///备注：
        ///{4} 的本地化字符串。
        /// </summary>
        internal static string funTmp {
            get {
                return ResourceManager.GetString("funTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///////////////////////////////////////////////////
        /////以下是关于【{0}】的所有事件和方法
        ///////////////////////////////////////////////////
        ///
        ///
        ///
        ///////////////////////////////////////////////////
        /////		方法列表
        ///////////////////////////////////////////////////
        ///
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string groupTitleATmp {
            get {
                return ResourceManager.GetString("groupTitleATmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///
        ///
        ///
        ///
        ///////////////////////////////////////////////////
        /////		事件列表
        ///////////////////////////////////////////////////
        ///
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string groupTitleBTmp {
            get {
                return ResourceManager.GetString("groupTitleBTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.读取配置文件：
        ///	方法一：使用菜单“文件/打开”。
        ///	方法二：直接把配置文件拖入应用程序。
        ///
        ///2.禁止软件启动时的自动更新检查:
        ///更改应用程序名，名字最后面带&quot;_nc&quot;（意为no check）
        ///如&quot;FlashInterfaceViewer_nc.exe&quot;
        ///这样就不会自动更新了。 的本地化字符串。
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///////////////////////////////////////////////////
        /////路径：{0}
        ///////////////////////////////////////////////////
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string itemTitleTmp {
            get {
                return ResourceManager.GetString("itemTitleTmp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MainICO {
            get {
                object obj = ResourceManager.GetObject("MainICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 	 * @param	{0} 的本地化字符串。
        /// </summary>
        internal static string paramTmp {
            get {
                return ResourceManager.GetString("paramTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	 * @return	{0} 的本地化字符串。
        /// </summary>
        internal static string returnTmp {
            get {
                return ResourceManager.GetString("returnTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/////////////////////////////////////////////////////////////////////
        ///	//{0}
        ///	/////////////////////////////////////////////////////////////////////
        ///	
        ///	
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string tileTmp {
            get {
                return ResourceManager.GetString("tileTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 			var {0}:{1} = e.data[{2}]; 的本地化字符串。
        /// </summary>
        internal static string varEventParamCode {
            get {
                return ResourceManager.GetString("varEventParamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 		代理类.{0}(&quot;{0}&quot;, this{1}); 的本地化字符串。
        /// </summary>
        internal static string vcListenerCode {
            get {
                return ResourceManager.GetString("vcListenerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本有更新
        ///现版本号：{0}/ 新版本号:{1}
        ///
        /////////////////更新日志///////////////
        ///{2}
        ////////////////////////////////////////
        ///
        ///点击确定将自动在后台自动更新，完成后将通知你。
        ///或点取消，然后向高帆索要最新文件。
        ///点击取消将不会自动更新。 的本地化字符串。
        /// </summary>
        internal static string versionUpdateMsg {
            get {
                return ResourceManager.GetString("versionUpdateMsg", resourceCulture);
            }
        }
    }
}
