//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4959
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMDEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string stirng {
            get {
                return ResourceManager.GetString("stirng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/**
        ///	 * $(EventTitle)
        ///	 * $(EventInfo)
        ///	 * @param	callBackName	事件处理函数的名字
        ///	 * @param	thisObj			事件处理函数所在的位置
        ///	 * @param	isRemove		是否移除这个事件，0默认为false
        ///	 */
        ///	public static function Event_$(EventName)(callBackName:String, thisObj:Object, isRemove:Boolean) {
        ///	
        ///		//事件接收的参数列表:
        ///		$(EventParametrs)
        ///		GCpp.eventListener(&quot;$(EventName)&quot;, thisObj, callBackName, isRemove);
        ///	} 的本地化字符串。
        /// </summary>
        internal static string Templet_Event {
            get {
                return ResourceManager.GetString("Templet_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/////////////////////////////////////////////////////////////////////
        ///	//						     VC事件
        ///	///////////////////////////////////////////////////////////////////// 的本地化字符串。
        /// </summary>
        internal static string Templet_EventFlag {
            get {
                return ResourceManager.GetString("Templet_EventFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Templet_Method {
            get {
                return ResourceManager.GetString("Templet_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 	/////////////////////////////////////////////////////////////////////
        ///	//						     测试相关
        ///	///////////////////////////////////////////////////////////////////// 的本地化字符串。
        /// </summary>
        internal static string Templet_TestFlag {
            get {
                return ResourceManager.GetString("Templet_TestFlag", resourceCulture);
            }
        }
    }
}
